version: '3.8'

services:
  trading-system:
    image: trading-system-unified:latest
    container_name: trading-system
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/app/startup.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=localhost
      - REDIS_PORT=6380
      - REDIS_PASSWORD=trading_system_2025
      - LOG_LEVEL=INFO
      # Enhanced GPU environment variables
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=0
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_GPU_THREAD_MODE=gpu_private
      - TF_GPU_THREAD_COUNT=8
      - TF_USE_CUDNN=1
      - TF_ENABLE_ONEDNN_OPTS=0
      - TF_XLA_FLAGS=--tf_xla_auto_jit=2
      - TF_TRT_ALLOW_ENGINE_NATIVE_SEGMENT=true
      - TENSORFLOW_INTRA_OP_PARALLELISM=4
      - TENSORFLOW_INTER_OP_PARALLELISM=4
      - PROMETHEUS_ENABLED=true
      - FRONTEND_WEBSOCKET_ENABLED=true
      - FRONTEND_REALTIME_UPDATES=true
      - METRICS_COLLECTION_INTERVAL=15
      - USE_TENSORRT_OPTIMIZATION=true
      - USE_REDIS_FALLBACK=true
      - SKIP_DEPENDENCIES_CHECK=false
      - DEBUG_MODE=true
    ports:
      - "5000:5000"   # Frontend
      - "6381:6380"   # Redis
      - "8000:8000"   # REST API
      - "8888:8888"   # Jupyter Lab
      - "9090:9090"   # Prometheus
      - "9121:9121"   # Redis Exporter
    volumes:
      - ./:/app/project
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
