"""
Results directory for the Autonomous Trading System.

This directory stores results and output files generated by the system,
including backtest results, performance metrics, and trading logs.
"""