server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://ats-loki-logs:3100/loki/api/v1/push

scrape_configs:
  # System container logs
  - job_name: system_controller_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: system_controller
        volumes:
          - /var/logs/system_controller/*.log:/var/logs/system_controller/*.log

  # Data acquisition logs
  - job_name: data_acquisition_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: data_acquisition
        volumes:
          - /var/logs/data_acquisition/*.log:/var/logs/data_acquisition/*.log

  # Trading strategy logs
  - job_name: trading_strategy_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: trading_strategy
        volumes:
          - /var/logs/trading_strategy/*.log:/var/logs/trading_strategy/*.log

  # Model training logs
  - job_name: model_training_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: model_training
        volumes:
          - /var/logs/model_training/*.log:/var/logs/model_training/*.log

  # Feature engineering logs
  - job_name: feature_engineering_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: feature_engineering
        volumes:
          - /var/logs/feature_engineering/*.log:/var/logs/feature_engineering/*.log

  # Continuous learning logs
  - job_name: continuous_learning_logs
    pipeline_stages:
      - json:
          expressions:
            component: component
            level: level
            message: message
            timestamp: timestamp
      - labels:
          component:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading_system
          component: continuous_learning
        volumes:
          - /var/logs/continuous_learning/*.log:/var/logs/continuous_learning/*.log

  # Docker container logs
  - job_name: docker_container_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log