global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '${SLACK_CHANNEL}'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        title_link: '${GRAFANA_URL:-http://127.0.0.1:3001}/d/trading-system/trading-system-dashboard'
        footer: 'Autonomous Trading System'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '${GRAFANA_URL:-http://127.0.0.1:3001}/d/trading-system/trading-system-dashboard'