# Prometheus configuration for trading system monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files to load
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Trading system metrics
  - job_name: "trading_system"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  # Redis exporter
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["localhost:9121"]

  # Node exporter for system metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
