version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: /app/logs/application.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /app/logs/application.json
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: /app/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  # System Controller
  system_controller:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

  # Data Acquisition
  data_acquisition:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  polygon_client:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  unusual_whales_client:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

  # Trading Strategy
  trading_strategy:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  alpaca_client:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

  # Model Training
  model_training:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  model_registry:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

  # Feature Engineering
  feature_engineering:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  feature_pipeline:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

  # Continuous Learning
  continuous_learning:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false
  
  performance_analyzer:
    level: INFO
    handlers: [console, file, json_file, error_file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
  propagate: true