groups:
  - name: trading_system_alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "Container {{ $labels.name }} has high CPU usage ({{ $value }})"

      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{name=~".+"}) by (name) / sum(container_spec_memory_limit_bytes{name=~".+"}) by (name) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Container {{ $labels.name }} has high memory usage ({{ $value }})"

      - alert: ContainerDown
        expr: absent(container_last_seen{name=~".+"})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container down"
          description: "Container {{ $labels.name }} is down"

      - alert: HighDatabaseConnections
        expr: sum(pg_stat_activity_count{datname="trading_system"}) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database has high number of connections ({{ $value }})"

      - alert: SlowDatabaseQueries
        expr: pg_stat_activity_max_tx_duration{datname="trading_system"} > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Database has slow queries running for more than 30 seconds"

      - alert: HighAPIErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API error rate"
          description: "API error rate is above 5% ({{ $value }})"

      - alert: HighAPILatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency"
          description: "95th percentile of API request duration is above 1 second ({{ $value }})"

      - alert: ModelInferenceLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(model_inference_duration_seconds_bucket[5m])) by (le, model)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High model inference latency"
          description: "95th percentile of model {{ $labels.model }} inference duration is above 0.5 seconds ({{ $value }})"

      - alert: TradingSignalGenerationStopped
        expr: rate(trading_signals_total[15m]) == 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "Trading signal generation stopped"
          description: "No trading signals have been generated in the last 15 minutes"

      - alert: HighTradeExecutionLatency
        expr: histogram_quantile(0.95, sum(rate(trade_execution_duration_seconds_bucket[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High trade execution latency"
          description: "95th percentile of trade execution duration is above 2 seconds ({{ $value }})"