version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --requirepass trading_system_2025
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "trading_system_2025", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    command: --redis.addr=redis://redis-cache:6379 --redis.password=trading_system_2025
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "9121:9121"
    networks:
      trading-network:

volumes:
  redis-data:

# Define networks to allow communication between separate docker-compose files
networks:
  trading-network:
    external: true