name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  verify:
    name: Verify Production Readiness
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Verify production readiness
        run: |
          chmod +x verify_production_readiness.sh
          ./verify_production_readiness.sh

  test:
    name: Run Tests
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run unit tests
        run: |
          python -m pytest tests/unit/

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.unified
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            inavvi/trading-system:latest
            inavvi/trading-system:${{ github.sha }}
          cache-from: type=registry,ref=inavvi/trading-system:buildcache
          cache-to: type=registry,ref=inavvi/trading-system:buildcache,mode=max

  deploy-staging:
    name: Deploy to Staging
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_target == 'staging')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /opt/inavvi
            docker-compose -f docker-compose.unified.yml down
            docker pull inavvi/trading-system:${{ github.sha }}
            echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" > .env
            echo "UNUSUAL_WHALES_API_KEY=${{ secrets.UNUSUAL_WHALES_API_KEY }}" >> .env
            echo "ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY }}" >> .env
            echo "ALPACA_API_SECRET=${{ secrets.ALPACA_API_SECRET }}" >> .env
            echo "ALPACA_API_URL=${{ secrets.ALPACA_API_URL }}" >> .env
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
            echo "USE_GPU=true" >> .env
            docker-compose -f docker-compose.unified.yml up -d
            ./manage_production.sh start

  deploy-production:
    name: Deploy to Production
    needs: deploy-staging
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_target == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            cd /opt/inavvi
            # Create backup before deployment
            ./backup_production_data.sh
            docker-compose -f docker-compose.unified.yml down
            docker pull inavvi/trading-system:${{ github.sha }}
            echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" > .env
            echo "UNUSUAL_WHALES_API_KEY=${{ secrets.UNUSUAL_WHALES_API_KEY }}" >> .env
            echo "ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY }}" >> .env
            echo "ALPACA_API_SECRET=${{ secrets.ALPACA_API_SECRET }}" >> .env
            echo "ALPACA_API_URL=${{ secrets.ALPACA_API_URL }}" >> .env
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
            echo "USE_GPU=true" >> .env
            docker-compose -f docker-compose.unified.yml up -d
            ./manage_production.sh start
            # Verify deployment
            ./monitor_production.sh